### ISSUE TITLE
iteration1 - 2 failing tests

### ISSUE THREAD

**Issue by jbrucker** [SoravitPete/ku-polls#16]
When I run your tests for iteration1 work (using the master branch)
the test output is:

test_future_question (polls.tests.QuestionDetailViewTests) ... ok
test_past_question (polls.tests.QuestionDetailViewTests) ... ok
test_future_question (polls.tests.QuestionIndexViewTests) ... FAIL
test_future_question_and_past_question (polls.tests.QuestionIndexViewTests) ... FAIL
test_no_questions (polls.tests.QuestionIndexViewTests) ... ok
test_past_question (polls.tests.QuestionIndexViewTests) ... ok
test_two_past_questions (polls.tests.QuestionIndexViewTests) ... ok
test_was_published_recently_with_old_question (polls.tests.QuestionModelTests) ... ok
test_was_published_recently_with_recent_question (polls.tests.QuestionModelTests) ... ok

======================================================================
FAIL: test_future_question (polls.tests.QuestionIndexViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Soravit/ku-polls/polls/tests.py", line 71, in test_future_question
    self.assertContains(response, "No polls are available.")
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 471, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'No polls are available.' in response

======================================================================
FAIL: test_future_question_and_past_question (polls.tests.QuestionIndexViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Soravit/ku-polls/polls/tests.py", line 84, in test_future_question_and_past_question
    ['<Question: Past question.>']
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 1072, in assertQuerysetEqual
    return self.assertEqual(list(items), values, msg=msg)
AssertionError: Lists differ: ['<Question: Future question.>', '<Question: Past question.>'] != ['<Question: Past question.>']

First differing element 0:
'<Question: Future question.>'
'<Question: Past question.>'

First list contains 1 additional elements.
First extra element 1:
'<Question: Past question.>'

- ['<Question: Future question.>', '<Question: Past question.>']
+ ['<Question: Past question.>']

----------------------------------------------------------------------
Ran 9 tests in 0.050s

FAILED (failures=2)

**Comment by SoravitPete** [comment]
Oh... OK thanks you very much. °Д°

ในวันที่ ศ. 17 ก.ย. 2021 13:34 James Brucker ***@***.***>
เขียนว่า:

**Comment by SoravitPete** [comment]
I fixed It. It fails because in Class DetailView get_queryset method In View.py Is still return the latest five publish question include the question that will publish in the future. :) Thank you very much.
